### ISSUE TITLE
Compiled DLL didn't work

### ISSUE THREAD

**Issue by Scrooge20291224** [ponapalt/yaya-shiori#11]
There were 3 warnings in the error list:
`
警告	MSB8012	TargetPath(E:\LostXmas\yaya-shiori-500\.\Debug\aya5.dll) 与 Linker 的 OutputFile 属性值(D:\ssp_src_set\ssp\ghost\DE10_3001\ghost\master\yaya.dll)不匹配。这可能导致项目生成不正确。若要更正此问题，请确保 $(OutDir)、$(TargetName) 和 $(TargetExt) 属性值与 %(Link.OutputFile) 中指定的值匹配。
`
`
警告	MSB8012	TargetName(aya5) 与 Linker 的 OutputFile 属性值(yaya)不匹配。这可能导致项目生成不正确。若要更正此问题，请确保 $(OutDir)、$(TargetName) 和 $(TargetExt) 属性值与 %(Link.OutputFile) 中指定的值匹配。
`
`
警告	LNK4075	忽略“/EDITANDCONTINUE”(由于“/SAFESEH”规范)
`
before replace original DLL (this means the dic files and other settings are functional):
![FirstAcquaintance - 副本](https://user-images.githubusercontent.com/10172485/56584776-0cfd9a00-660f-11e9-98f7-36ff2153d84f.png)

after replacing Shiori, shell and ssp are still working but ghost make no reactions for any interaction (click/double click/collision)

**Comment by Scrooge20291224** [comment]
Before this compilation, I've encountered 2 major errors:
1.shift jis code error: in order to cover this, I've converted all Japanese string into unicode
2.I replace the inclusion of "afxres.h" with "winres.h"
Maybe these changes are relative to this issue?

**Comment by ponapalt** [comment]
I have modified code to avoid sjis code problem, include file, and other build problem.
Please try latest source code.

**Comment by Scrooge20291224** [comment]
> I have modified code to avoid sjis code problem, include file, and other build problem.
> Please try latest source code.

Thanks, the compilation is normal, but, DLL is still dysfunctional, Sorry.
Release output 1612k dll file (without UPX compression), I wonder whether the compression is used or not will affect the running?
Thank you for your reply.

**Comment by ponapalt** [comment]
I think that UPX or other executable compressors doesn't affect DLL machine code.
Please send me problematic binary output files not just DLL but symbol file (pdb and map). I'll debug it directly.

**Comment by Scrooge20291224** [comment]
> I think that UPX or other executable compressors doesn't affect DLL machine code.
> Please send me problematic binary output files not just DLL but symbol file (pdb and map). I'll debug it directly.

Thx and sorry for my late reply
Can you give me an E-mail address to sent archieved filed (the whole project)?
Thx for your continuous helping!

**Comment by ponapalt** [comment]
My e-mail address is : ponapalt@shillest.net
But I think that sending DLL files via e-mail is problematic because of false-positive of virus checker.
We should use network drive service such as OneDrive or DropBox.

**Comment by Scrooge20291224** [comment]
> ponapalt@shillest.net

here is the link of OneDrive
https://1drv.ms/u/s!AmxFGBbCiFCphU3yJ15DYXBTLWz9

Thank you for your helping! I hope I can make a runnable shiori XD

**Comment by ponapalt** [comment]
I have commited aya5.vcxproj just now to fix this problem.

Details of change :
I have added /source-charset and /execution-charset options to compile shift-jis source code
rather than converting source code to UTF-8, because of other compiler compatibility.

**Comment by Scrooge20291224** [comment]
> I have commited aya5.vcxproj just now to fix this problem.
> 
> Details of change :
> I have added /source-charset and /execution-charset options to compile shift-jis source code
> rather than converting source code to UTF-8, because of other compiler compatibility.

Thx, I will have a try soon    o(∩_∩)o
