### ISSUE TITLE
I have a question about the using of RE_GREP

### ISSUE THREAD

**Issue by Scrooge20291224** [ponapalt/yaya-shiori#12]
I want to extract sub-strings quoted by double quotation marks from a long dialog
My code:
`_count=RE_GREP(_script,"\"*\"");`
`_script=RE_GETSTR;`
My RE pattern is:
`\"*\"`
I want to mark " as a text char, so I add \ before it in order to translate it, however, I get this error from TAMA:
`E:\LostXmas\cssp\ghost\LostXmas\ghost\master\RPYParser.dic(30) : error E0011 : 変数名(?)に使用できない文字が含まれています. : \""`

It looks like the dictionary syntax cannot recognize \" as a translated pure text "
I eagerly hope anyone can tell me how to translate a double quotation mark into a pure text char, I would really appreciate it.

**Comment by ponapalt** [comment]
How about this?

"\%(CHR(34))*\%(CHR(34))"

34 is ASCII code for double quote, and CHR is system function converting ascii code to string.

**Comment by Scrooge20291224** [comment]
> How about this?
> 
> "%(CHR(34))*%(CHR(34))"
> 
> 34 is ASCII code for double quote, and CHR is system function converting ascii code to string.

That did work! thank you very much! XD
