### ISSUE TITLE
yayaをpluginとして使用する際に、OnOtherGhostTalk関数が自分のトークも拾ってしまう。

### ISSUE THREAD

**Issue by ambergon** [ponapalt/yaya-shiori#38]
下記のようにしたときに永遠とカウントをバルーンに表示し続けた。
```辞書 
version {
	"origin/1.0"
}
OnPluginLoad.Self {
    i = 0
}
OnOtherGhostTalk {
    i++
    i
}
```
```.descript.txt
otherghosttalk,after
```

**Comment by nikolat** [comment]
http://ssp.shillest.net/ukadoc/manual/list_plugin_event.html#OnOtherGhostTalk
PLUGINはGHOSTではないので「自分」という概念は無いです。
起動中のゴーストはPLUGINにとって全て他人であり、全てのトークを拾います。
そのイベント内でスクリプトを返せば当然無限にループします。

**Comment by ambergon** [comment]
やっぱり自分の概念はないんですね。
ありがとうございます。

**Comment by nikolat** [comment]
どういった利用を想定しているかわからないですが、
OnOtherGhostTalk の Reference2 に
```
プラグインからのスクリプトの場合、plugin-script
プラグインからのイベント反応の場合、plugin-event
```
とあるので、これを見てスクリプトを返さない、とすればループを回避できると思います。
