### ISSUE TITLE
The return value of CHARSETLIBEX

### ISSUE THREAD

**Issue by nikolat** [ponapalt/yaya-shiori#39]
If code is specified, the return value of CHARSETLIBEX should be VOID, but actually a value is returned.
https://emily.shillest.net/ayaya/?%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB/%E9%96%A2%E6%95%B0/CHARSETLIBEX

**Comment by ponapalt** [comment]
[Tc571-6](https://github.com/YAYA-shiori/yaya-shiori/releases/tag/Tc571-6)
